### ISSUE TITLE
Feature request: remember sort order when spellbook is launched from macro button

### ISSUE THREAD

**Issue by rogue-ronin** [Merudo/spell-library#1]
Would it be possible to have the library remember your sort order per-token?

Currently, when you launch the macro it sorts by the second column "Name". I prefer to sort by name within level and with level sorted from lowest to highest. This is a fairly easy 2-click sort, but having to do it every time... :)

Note also that if the spellbook is open and you click the macro-button it re-sorts the spellbook to alphabetical. (I assume it is re-opening the spellbook.)

Thanks for your consideration, and

Aloha!

**Comment by Merudo** [comment]
Feature added by 016d917
